try {
    ${1}
} catch (Exception $e) {
    
}
